file(GLOB shaders ${INPUT_DIR}/*.vert ${INPUT_DIR}/*.frag)
message(STATUS "output directory ${OUTPUT_DIR}")
foreach (shader ${shaders})
    get_filename_component(shader_name ${shader} NAME)
    message(STATUS "compiling ${shader_name}")
    execute_process(COMMAND glslc.exe ${shader} -o ${OUTPUT_DIR}/${shader_name}.spv)
endforeach()
## because visual studio projects create additional Debug and Release folders in binary directory
if (EXISTS ${OUTPUT_DIR}/Debug)
    list(APPEND output_dirs ${OUTPUT_DIR}/Debug)
endif()
if (EXISTS ${OUTPUT_DIR}/debug)
    list(APPEND output_dirs ${OUTPUT_DIR}/debug)
endif()
if (EXISTS ${OUTPUT_DIR}/Release)
    list(APPEND output_dirs ${OUTPUT_DIR}/Release)
endif()
if (EXISTS ${OUTPUT_DIR}/release)
    list(APPEND output_dirs ${OUTPUT_DIR}/release)
endif()
file(GLOB shaders ${OUTPUT_DIR}/*.spv)
foreach (directory ${output_dirs})
    message(STATUS "copy ${shaders} to ${directory}")
    foreach (shader ${shaders})
        file(COPY ${shader} DESTINATION ${directory})
    endforeach()
endforeach()